kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
    name: "ulikeit-database"
    namespace: "default"
    labels:
        team: ulikeit

spec:
    teamId: "ulikeit"
    postgresql:
        version: "13"
    numberOfInstances: 1
    enableConnectionPooler: true
    volume:
        size: "10Gi"
    users:
        keycloak:
            - superuser
            - createdb
        session:
            - superuser
            - createdb
        storage:
            - superuser
            - createdb
    databases:
        keycloak: keycloak
        session: session
        storage: storage
    allowedSourceRanges: # load balancers' source ranges for both master and replica services
        - 192.168.0.0/18
        - 192.168.64.0/18
        - 192.168.128.0/18
    resources:
        requests:
            cpu: 100m
            memory: 100Mi
        limits:
            cpu: 500m
            memory: 500Mi
