kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
    name: "ulikeit-database"
    namespace: "default"
    labels:
        team: ulikeit

spec:
    teamId: "ulikeit"
    postgresql:
        version: "13"
        parameters: # Expert section
            shared_buffers: "32MB"
            max_connections: "250"
            log_statement: "all"
    numberOfInstances: 3
    enableConnectionPooler: true
    enableLogicalBackup: true
    volume:
        size: "10Gi"
    users:
        keycloak:
            - superuser
            - createdb
            - login
            - createrole
        session:
            - superuser
            - createdb
            - login
            - createrole
        storage:
            - superuser
            - createdb
            - login
            - createrole
    databases:
        keycloak: keycloak
        session: session
        storage: storage
    allowedSourceRanges: # load balancers' source ranges for both master and replica services
        - 10.100.0.1/18
        - 10.100.64.0/18
        - 10.100.128.0/18
        - 10.100.192.0/18
        - 10.100.256.0/18
    resources:
        requests:
            cpu: 100m
            memory: 100Mi
        limits:
            cpu: 500m
            memory: 500Mi
    patroni:
        initdb:
            encoding: "UTF8"
            locale: "de_DE.UTF-8"
            data-checksums: "true"
        pg_hba:
          - hostssl all all 0.0.0.0/0 md5
          - host    all all 0.0.0.0/0 md5
          - local   all all trust
    #    slots:
    #      permanent_physical_1:
    #        type: physical
    #      permanent_logical_1:
    #        type: logical
    #        database: foo
    #        plugin: pgoutput
        ttl: 30
        loop_wait: &loop_wait 10
        retry_timeout: 10
        synchronous_mode: false
        synchronous_mode_strict: false
        maximum_lag_on_failover: 33554432
