name: keycloak-pipeline
on:
    push:
        branches:
            - production
jobs:
    release-authorization:
        runs-on: ubuntu-latest
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Read version.yaml
              id: version
              uses: juliangruber/read-file-action@v1
              with:
                  path: ./version.yaml

            - name: Create databases
              uses: kenju/kubernetes-action@master
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
              with:
                  args: apply -f ./databases.yaml

#            - name: Configure AWS credentials
#              uses: aws-actions/configure-aws-credentials@v1
#              with:
#                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#                aws-region: ${{ secrets.AWS_REGION }}
#
#            - name: Login to Amazon ECR
#              id: login-ecr
#              uses: aws-actions/amazon-ecr-login@v1
#
#            - name: Build, tag, and push image to Amazon ECR
#              env:
#                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#                ECR_REPOSITORY: ulikeit-keycloak-metrics-spi
#                IMAGE_TAG: ${{ steps.version.outputs.content }}
#              run: |
#                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg app_version="${{ steps.version.outputs.content }}" --build-arg auth_token="${{ secrets.REPO_TOKEN }}" .
#                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG




            - run: echo "🎉 The keycloak deployment is finished."
